### ISSUE TITLE
General comments

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-geodecision#2]
- [x] Do we need [.github directory](https://github.com/VCityTeam/UD-geodecision/tree/master/.github) ?
 - [x] [Dashboard directory](https://github.com/VCityTeam/UD-geodecision/tree/master/dashboard) will be removed to become a docker.
 - [x] They are as many copies of GeoDecision sources as they are contexts (e.g. [here](https://github.com/VCityTeam/UD-geodecision/tree/master/docker/Dashboard_DockerContext/geodecision), [there](https://github.com/VCityTeam/UD-geodecision/tree/master/docker/FormatAndAnalyseRoofs/geodecision)...) Respect DRY principle and have a unique version of GeoDecision sources. Refer below on how to deal with credentials. PARTLY DEPORTED TO issue #6
 - [x] Use [UD-geodecision-docker](https://github.com/VCityTeam/UD-geodecision-docker/) to cpy docker content
 - [x] FormatAndAnalyseRoofs' Dockefile should cleanly (pip) install geodecision (as opposed to copying files around) DEPORTED TO issue #10
 - [x] Fix the FIXME in `UD-geodecision-docker/FormatAndAnalyseRoofs/DockerContext/entrypoint.py` => ***Fixed, see [commit](https://github.com/VCityTeam/UD-geodecision-docker/commit/d334c03cd47c8b17e3a20a0a87f576f87edb42d3)***
 - [x] Clean up the `UD-geodecision-docker/FormatAndAnalyseRoofs/DockerContext/Dockefile` (refer to comments) and lighten the too numerous conda downloaded packages PARTLY DEPORTED TO issue #11
- [x] Use ```pip install . ``` to install geodecision package instead of "path importation" (*implies to modify Python files that import geodecision*) DEPORTED TO issue #9 
- [x]  The way of the docker wrapping out of GeoDecision repository 
   DEPORTED TO issue #13
